export const ACTION_TYPES = {
    INCREASE_COUNTER_A: 'INCREASE_COUNTER_A',
    INCREASE_COUNTER_B: 'INCREASE_COUNTER_B',
    INCREASE_QUANTITY: 'INCREASE_QUANTITY',
    SWAP_ACADEMY_ADDRESS: 'SWAP_ACADEMY_ADDRESS',
    CHANGE_ACADEMY_NAME: 'CHANGE_ACADEMY_NAME',
    USER_FETCH_SUCCEEDED: 'USER_FETCH_SUCCEEDED',
    USER_FETCH_FAILED: 'USER_FETCH_FAILED',
    USER_FETCH_REQUESTED: 'USER_FETCH_REQUESTED',
};