export const ACTION_TYPES = {
    INCREASE_COUNTER_A: 'INCREASE_COUNTER_A',
    INCREASE_COUNTER_B: 'INCREASE_COUNTER_B',
    INCREASE_QUANTITY: 'INCREASE_QUANTITY',
    SWAP_ACADEMY_ADDRESS: 'SWAP_ACADEMY_ADDRESS',
};